export const reservasForm = [
    {
        id: 0,
        name: "numeroContrato",
        label: "Numero Contrato",
        type: "number",
        placeholder: "numero Contrato",
        description: "numero Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "documentoCliente",
        label: "Documento Cliente (DNI)",
        type: "number",
        placeholder: "Documento Cliente",
        description: "Documento Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "nombresCliente",
        label: "Nombres Cliente",
        type: "text",
        placeholder: "Nombres Cliente",
        description: "Nombres Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "apellidoPaternoCliente",
        label: "Apellido Paterno",
        type: "text",
        placeholder: "Apellido Paterno Cliente",
        description: "Apellido Paterno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "apellidoMaternoCliente",
        label: "Apellido Materno",
        type: "text",
        placeholder: "Apellido Materno Cliente",
        description: "Apellido Materno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "tarifaContrato",
        label: "Tarifa Contrato S/.",
        type: "number",
        placeholder: "tarifa Contrato",
        description: "tarifa Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "celular",
        label: "Celular Cliente",
        type: "number",
        placeholder: "Celular Cliente",
        description: "Celular Cliente",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 7,
        name: "ruc",
        label: "RUC",
        type: "number",
        placeholder: "RUC",
        description: "RUC",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 8,
        name: "razonSocial",
        label: "Razón Social",
        type: "text",
        placeholder: "Razón Social",
        description: "Razón Social",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 7,
        name: "comentario",
        label: "comentario",
        type: "text",
        multiline: true,
        rows: 2,
        placeholder: "comentario",
        description: "comentario",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formLogin = [
    {
        id: 0,
        name: "documentoUsuario",
        label: "numero Documento",
        type: "number",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }],
        placeholder: "numero Documento",
        description: "numero Documento",
        multiline: false,
        rows: 3,
        disabled: false,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "password",
        label: "password",
        type: "password",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }],
        placeholder: "password",
        description: "password",
        multiline: false,
        rows: 3,
        disabled: false,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formRealizaPedidos = [
    {
        id: 10,
        name: "fechaPedido",
        label: "Fecha de Pedido",
        type: "text",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
        placeholder: "Fecha de Pedido",
        description: "Fecha de Pedido",
        multiline: false,
        rows: 3,
        disabled: true,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 10,
        name: "fechaEntregaPedido",
        label: "Fecha Entrega Pedido",
        type: "text",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
        placeholder: "Fecha Entrega Pedido",
        description: "Fecha Entrega Pedido",
        multiline: false,
        rows: 3,
        disabled: true,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 0,
        name: "cantidadPaquetes",
        label: "Seleccionar Paquetes",
        type: "select",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
        placeholder: "Seleccionar Paquetes",
        description: "Seleccionar Paquetes",
        multiline: false,
        rows: 3,
        disabled: false,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "kilos",
        label: "Kilos",
        type: "number",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
        placeholder: "Kilos",
        description: "Kilos",
        multiline: false,
        rows: 3,
        disabled: true,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "precioSemanal",
        label: "Precio Semanal S/.",
        type: "number",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
        placeholder: "Precio Semanal S/.",
        description: "Precio Semanal S/.",
        multiline: false,
        rows: 3,
        disabled: true,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "medioPago",
        label: "Seleccione Medio de Pago",
        type: "select",
        options: [{ value: "1", label: "Efectivo" }, { value: "2", label: "Yape/Transferencia" }],
        placeholder: "Medio de Pago",
        description: "Medio de Pago",
        multiline: false,
        rows: 3,
        disabled: false,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precio",
        label: "Precio S/.",
        type: "text",
        options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
        placeholder: "Precio S/.",
        description: "Precio S/.",
        multiline: false,
        rows: 3,
        disabled: true,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 5,
    //     name: "precioConFactura",
    //     label: "Precio con Factura S/.",
    //     type: "text",
    //     options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
    //     placeholder: "Precio con Factura S/.",
    //     description: "Precio con Factura S/.",
    //     multiline: false,
    //     rows: 3,
    //     disabled: true,
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 5,
    //     name: "precioConFactura",
    //     label: "Precio con Factura S/.",
    //     type: "text",
    //     options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
    //     placeholder: "Precio con Factura S/.",
    //     description: "Precio con Factura S/.",
    //     multiline: false,
    //     rows: 3,
    //     disabled: true,
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 5,
        name: "lugarEntrega",
        label: "Lugar de Entrega",
        type: "select",
        options: [{ value: "1", label: "Domicilio (+6.00)" }, { value: "2", label: "Oficina Orbes" }],
        placeholder: "Lugar de Entrega",
        description: "Lugar de Entrega",
        multiline: false,
        rows: 3,
        disabled: false,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 6,
    //     name: "direccionEntrega",
    //     label: "Direccion Entrega",
    //     type: "text",
    //     options: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }],
    //     placeholder: "Detallar la direccion con referencia a la calle/numero/avenida/etc.",
    //     description: "Direccion Entrega",
    //     multiline: true,
    //     rows: 3,
    //     disabled: false,
    //     required: false,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 7,
        name: "pagoTotal",
        label: "Total a pagar S/. Pago Contraentrega",
        type: "number",
        options: [{ value: "1", label: "Domicilio" }, { value: "2", label: "Oficina Orbes" }],
        placeholder: "Total a pagar S/.",
        description: "Total a pagar S/.",
        multiline: false,
        rows: 3,
        disabled: true,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formEditarStatusHabitacion = [
    {
        id: 0,
        name: "estadoHabitacion",
        label: "Estado de HAbitación",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "Disponible" },
            { value: "1", label: "Ocupada" },
            { value: "2", label: "Sucia" },
            { value: "3", label: "No Disponible" },
            { value: "4", label: "Reservada" },
        ],
        placeholder: "Estado de HAbitación",
        description: "Estado de HAbitación",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 22,
        name: "tipoRetiroHoy",
        label: "tipo Retiro",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "R" },
            { value: "1", label: "R HOY" },
        ],
        placeholder: "tipo Retiro",
        description: "tipo Retiro",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "piso",
        label: "piso",
        type: "number",
        // options: ["Asesor Antiguo", "Asesor Nuevo"],
        placeholder: "piso",
        description: "piso",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
        disabled: false
    },
    {
        id: 2,
        name: "tipoHabitacion",
        label: "tipo Habitacion",
        type: "select",
        options: [
            { value: "simple", label: "Simple" },
            { value: "matrimonial", label: "Matrimonial" },
            { value: "doble", label: "Doble" },
            { value: "triple", label: "Triple" },
        ],
        placeholder: "tipo Habitacion",
        description: "tipo Habitacion",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
        disabled: false
    },
    {
        id: 3,
        name: "capacidad",
        label: "capacidad",
        type: "text",
        // options: ["Asesor Antiguo", "Asesor Nuevo"],
        placeholder: "capacidad",
        description: "capacidad",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
        disabled: false
    },
    {
        id: 4,
        name: "precioBase",
        label: "precio Base",
        type: "text",
        // options: ["Asesor Antiguo", "Asesor Nuevo"],
        placeholder: "precio Base",
        description: "precio Base",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
        disabled: false
    },
    {
        id: 5,
        name: "amenidades",
        label: "amenidades",
        type: "selectMultiple",
        options: [
            // {
            //     id: 0,
            //     description: "wifi",
            //     name: "Wifi",
            // },
            {
                id: 1,
                description: "friobar",
                name: "Friobar",
            },
            {
                id: 2,
                description: "aireacondicionado",
                name: "Aire Acondicionado",
            },
            {
                id: 3,
                description: "tvsmart",
                name: "TV Smart",
            },
        ],
        placeholder: "amenidades",
        // description: "amenidades",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
        disabled: false
    },
    {
        id: 6,
        name: "descripcion",
        label: "descripcion",
        type: "text",
        // options: ["Asesor Antiguo", "Asesor Nuevo"],
        placeholder: "descripcion",
        description: "descripcion",
        required: false,
        multiline: true,
        rows: 3,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
        disabled: false
    },
]

export const formEditContrato = [
    {
        id: 0,
        name: "numeroContrato",
        label: "Numero Contrato",
        type: "number",
        placeholder: "numero Contrato",
        description: "numero Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 55,
        name: "statusContrato",
        label: "status Contrato",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "Retirado" },
            { value: "1", label: "Ocupado" },
            { value: "2", label: "Reservado" },
        ],
        placeholder: "status Contrato",
        description: "status Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "numeroHabitacion",
        label: "Numero Habitacion",
        type: "number",
        placeholder: "numero Habitacion",
        description: "numero Habitacion",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "tarifaContrato",
        label: "Tarifa Contrato S/.",
        type: "number",
        placeholder: "tarifa Contrato",
        description: "tarifa Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formEditContratoClientes = [
    {
        id: 0,
        name: "documentoCliente",
        label: "Documento Cliente (DNI)",
        type: "number",
        placeholder: "Documento Cliente",
        description: "Documento Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "nombresCliente",
        label: "Nombres Cliente",
        type: "text",
        placeholder: "Nombres Cliente",
        description: "Nombres Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "apellidoPaternoCliente",
        label: "Apellido Paterno",
        type: "text",
        placeholder: "Apellido Paterno Cliente",
        description: "Apellido Paterno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "apellidoMaternoCliente",
        label: "Apellido Materno",
        type: "text",
        placeholder: "Apellido Materno Cliente",
        description: "Apellido Materno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "celular",
        label: "Celular Cliente",
        type: "number",
        placeholder: "Celular Cliente",
        description: "Celular Cliente",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 7,
        name: "ruc",
        label: "RUC",
        type: "number",
        placeholder: "RUC",
        description: "RUC",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 8,
        name: "razonSocial",
        label: "Razón Social",
        type: "text",
        placeholder: "Razón Social",
        description: "Razón Social",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formEditConsumoAlojamiento = [
    {
        id: 0,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "fechaFin",
        label: "fecha Fin",
        type: "date",
        placeholder: "fecha Fin",
        description: "fecha Fin",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "precio",
        label: "precio",
        type: "number",
        placeholder: "precio",
        description: "precio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "comentario",
        label: "comentario",
        type: "text",
        placeholder: "comentario",
        description: "comentario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formEditConsumoAlojamiento2 = [
    {
        id: 0,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "fechaFin",
        label: "fecha Fin",
        type: "date",
        placeholder: "fecha Fin",
        description: "fecha Fin",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioVenta",
        label: "Precio Total",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 5,
    //     name: "comentario",
    //     label: "comentario",
    //     type: "text",
    //     placeholder: "comentario",
    //     description: "comentario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formEditConsumosVarios = [
    {
        id: 0,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "item",
        label: "item",
        type: "text",
        placeholder: "item",
        description: "item",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "precioUnitario",
        label: "precio Unitario",
        type: "number",
        placeholder: "precio Unitario",
        description: "precio Unitario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "cantidad",
        label: "cantidad",
        type: "number",
        placeholder: "cantidad",
        description: "cantidad",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioTotal",
        label: "Total",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "comentario",
        label: "comentario",
        type: "text",
        placeholder: "comentario",
        description: "comentario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formEditCajas = [
    {
        id: 0,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "cantidad",
        label: "monto",
        type: "number",
        placeholder: "monto",
        description: "monto",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "concepto",
        label: "concepto",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "Alojamiento" },
            { value: "1", label: "Bazar" },
            { value: "2", label: "Baño" },
            { value: "3", label: "Lavanderia" },
            { value: "4", label: "Vuelto" },
            { value: "5", label: "Extra Igv" },
            { value: "6", label: "Otros" },
        ],
        placeholder: "concepto",
        description: "concepto",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "comentario",
        label: "comentario",
        type: "text",
        placeholder: "comentario",
        description: "comentario",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formNumeroBoletaFactura = [
    {
        id: 2,
        name: "numeroBoletaFactura",
        label: "numero Boleta/Factura",
        type: "text",
        placeholder: "numero Boleta/Factura",
        description: "numero Boleta/Factura",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formRetiro = [
    {
        id: 0,
        name: "tipoRetiroHoy",
        label: "tipo Retiro",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "R" },
            { value: "1", label: "R HOY" },
        ],
        placeholder: "tipo Retiro",
        description: "tipo Retiro",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const reservasFormReservas = [
    {
        id: 0,
        name: "numeroContrato",
        label: "Numero Contrato",
        type: "number",
        placeholder: "numero Contrato",
        description: "numero Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 11,
        name: "numeroHabitacion",
        label: "Numero Habitacion",
        type: "text",
        placeholder: "numero Habitacion",
        description: "numero Habitacion",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 22,
        name: "fechaReserva",
        label: "fecha Reserva",
        type: "date",
        placeholder: "fecha Reserva",
        description: "fecha Reserva",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "documentoCliente",
        label: "Documento Cliente (DNI)",
        type: "number",
        placeholder: "Documento Cliente",
        description: "Documento Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "nombresCliente",
        label: "Nombres Cliente",
        type: "text",
        placeholder: "Nombres Cliente",
        description: "Nombres Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "apellidoPaternoCliente",
        label: "Apellido Paterno",
        type: "text",
        placeholder: "Apellido Paterno Cliente",
        description: "Apellido Paterno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "apellidoMaternoCliente",
        label: "Apellido Materno",
        type: "text",
        placeholder: "Apellido Materno Cliente",
        description: "Apellido Materno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "tarifaContrato",
        label: "Tarifa Contrato S/.",
        type: "number",
        placeholder: "tarifa Contrato",
        description: "tarifa Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "celular",
        label: "Celular Cliente",
        type: "number",
        placeholder: "Celular Cliente",
        description: "Celular Cliente",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formEditContratoReserva = [
    {
        id: 0,
        name: "numeroContrato",
        label: "Numero Contrato",
        type: "number",
        placeholder: "numero Contrato",
        description: "numero Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 55,
        name: "statusContrato",
        label: "status Contrato",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "Retirado" },
            { value: "1", label: "Ocupado" },
            { value: "2", label: "Reservado" },
        ],
        placeholder: "status Contrato",
        description: "status Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "numeroHabitacion",
        label: "Numero Habitacion",
        type: "number",
        placeholder: "numero Habitacion",
        description: "numero Habitacion",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 22,
        name: "fechaReserva",
        label: "fecha Reserva",
        type: "date",
        placeholder: "fecha Reserva",
        description: "fecha Reserva",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "tarifaContrato",
        label: "Tarifa Contrato S/.",
        type: "number",
        placeholder: "tarifa Contrato",
        description: "tarifa Contrato",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formBazar = [
    // {
    //     id: 0,
    //     name: "fechaInicio",
    //     label: "fecha Inicio",
    //     type: "date",
    //     placeholder: "fecha Inicio",
    //     description: "fecha Inicio",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 1,
        name: "nombreProducto",
        label: "item",
        type: "select",
        placeholder: "item",
        description: "item",
        multiline: true,
        rows: 3,
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "precioUnitario",
        label: "precio Unitario",
        type: "number",
        placeholder: "precio Unitario",
        description: "precio Unitario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "cantidad",
        label: "cantidad",
        type: "number",
        placeholder: "cantidad",
        description: "cantidad",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioVenta",
        label: "Precio Total",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        disabled: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 5,
    //     name: "comentario",
    //     label: "comentario",
    //     type: "text",
    //     placeholder: "comentario",
    //     description: "comentario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formBazarExterno = [
    // {
    //     id: 0,
    //     name: "fechaInicio",
    //     label: "fecha Inicio",
    //     type: "date",
    //     placeholder: "fecha Inicio",
    //     description: "fecha Inicio",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 1,
        name: "nombreProducto",
        label: "item",
        type: "select",
        placeholder: "item",
        description: "item",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "precioUnitario",
        label: "precio Unitario",
        type: "number",
        placeholder: "precio Unitario",
        description: "precio Unitario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "cantidad",
        label: "cantidad",
        type: "number",
        placeholder: "cantidad",
        description: "cantidad",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioVenta",
        label: "Precio Total",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        disabled: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "comentario",
        label: "comentario",
        type: "text",
        placeholder: "comentario",
        description: "comentario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formAgregarNewProductoInventario = [
    {
        id: 1,
        name: "nombreProducto",
        label: "Nombre Producto",
        type: "text",
        placeholder: "nombre Producto",
        description: "nombre Producto",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "descripcion",
        label: "Descripcion",
        type: "text",
        placeholder: "descripcion",
        description: "descripcion",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "stock",
        label: "Stock",
        type: "number",
        placeholder: "Stock",
        description: "Stock",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioCompra",
        label: "Precio Compra",
        type: "number",
        placeholder: "precio Compra",
        description: "precio Compra",
        required: true,
        disabled: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "precioVenta",
        label: "Precio Venta",
        type: "number",
        placeholder: "precio Venta",
        description: "precio Venta",
        required: true,
        disabled: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "categoria",
        label: "Categoria",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "Snacks" },
            { value: "1", label: "Bebidas" },
            { value: "2", label: "Aseso" },
            { value: "3", label: "Otros" },
        ],
        placeholder: "categoria",
        description: "categoria",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 7,
    //     name: "factura",
    //     label: "Factura",
    //     type: "text",
    //     placeholder: "factura",
    //     description: "factura",
    //     required: true,
    //     disabled: false,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
]

export const formEditarProductoInventario = [
    {
        id: 1,
        name: "nombreProducto",
        label: "Nombre Producto",
        type: "text",
        placeholder: "nombre Producto",
        description: "nombre Producto",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "descripcion",
        label: "Descripcion",
        type: "text",
        placeholder: "descripcion",
        description: "descripcion",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "precioVenta",
        label: "Precio Venta",
        type: "number",
        placeholder: "precio Venta",
        description: "precio Venta",
        required: true,
        disabled: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "categoria",
        label: "Categoria",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "Snacks" },
            { value: "1", label: "Bebidas" },
            { value: "2", label: "Aseso" },
            { value: "3", label: "Otros" },
        ],
        placeholder: "categoria",
        description: "categoria",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 7,
    //     name: "factura",
    //     label: "Factura",
    //     type: "text",
    //     placeholder: "factura",
    //     description: "factura",
    //     required: true,
    //     disabled: false,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
]

export const formEditarStockProducto = [
    {
        id: 1,
        name: "cantidad",
        label: "Cantidad",
        type: "number",
        placeholder: "Cantidad",
        description: "Cantidad",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formLavanderia = [
    // {
    //     id: 0,
    //     name: "fechaInicio",
    //     label: "fecha Inicio",
    //     type: "date",
    //     placeholder: "fecha Inicio",
    //     description: "fecha Inicio",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 1,
        name: "nombreProducto",
        label: "item",
        type: "text",
        placeholder: "item",
        description: "item",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "precioUnitario",
        label: "precio Unitario",
        type: "number",
        placeholder: "precio Unitario",
        description: "precio Unitario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "cantidad",
        label: "cantidad",
        type: "number",
        placeholder: "cantidad",
        description: "cantidad",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioVenta",
        label: "Precio Total",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 5,
    //     name: "comentario",
    //     label: "comentario",
    //     type: "text",
    //     placeholder: "comentario",
    //     description: "comentario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formExtraIgv = [
    // {
    //     id: 0,
    //     name: "fechaInicio",
    //     label: "fecha Inicio",
    //     type: "date",
    //     placeholder: "fecha Inicio",
    //     description: "fecha Inicio",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 1,
        name: "nombreProducto",
        label: "item",
        type: "text",
        placeholder: "item",
        description: "item",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 3,
    //     name: "precioUnitario",
    //     label: "precio Unitario",
    //     type: "number",
    //     placeholder: "precio Unitario",
    //     description: "precio Unitario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 2,
    //     name: "cantidad",
    //     label: "cantidad",
    //     type: "number",
    //     placeholder: "cantidad",
    //     description: "cantidad",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 4,
        name: "precioVenta",
        label: "Precio Total",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 5,
    //     name: "comentario",
    //     label: "comentario",
    //     type: "text",
    //     placeholder: "comentario",
    //     description: "comentario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formVuelto = [
    // {
    //     id: 0,
    //     name: "fechaInicio",
    //     label: "fecha Inicio",
    //     type: "date",
    //     placeholder: "fecha Inicio",
    //     description: "fecha Inicio",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 1,
    //     name: "nombreProducto",
    //     label: "item",
    //     type: "text",
    //     placeholder: "item",
    //     description: "item",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 3,
    //     name: "precioUnitario",
    //     label: "precio Unitario",
    //     type: "number",
    //     placeholder: "precio Unitario",
    //     description: "precio Unitario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 2,
    //     name: "cantidad",
    //     label: "cantidad",
    //     type: "number",
    //     placeholder: "cantidad",
    //     description: "cantidad",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 4,
        name: "precioVenta",
        label: "Monto de Vuelto",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            // { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "comentario",
        label: "comentario",
        type: "text",
        placeholder: "comentario",
        description: "comentario",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formOtrosIngresosEgresosBano = [
    {
        id: 0,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 1,
    //     name: "item",
    //     label: "item",
    //     type: "text",
    //     placeholder: "item",
    //     description: "item",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 3,
    //     name: "precioUnitario",
    //     label: "precio Unitario",
    //     type: "number",
    //     placeholder: "precio Unitario",
    //     description: "precio Unitario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 2,
    //     name: "cantidad",
    //     label: "cantidad",
    //     type: "number",
    //     placeholder: "cantidad",
    //     description: "cantidad",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 4,
        name: "precioTotal",
        label: "Total",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 5,
    //     name: "comentario",
    //     label: "comentario",
    //     type: "text",
    //     placeholder: "comentario",
    //     description: "comentario",
    //     required: true,
    //     multiline: true,
    //     rows: 3,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formOtrosIngresos = [
    {
        id: 0,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 1,
    //     name: "item",
    //     label: "item",
    //     type: "text",
    //     placeholder: "item",
    //     description: "item",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 3,
    //     name: "precioUnitario",
    //     label: "precio Unitario",
    //     type: "number",
    //     placeholder: "precio Unitario",
    //     description: "precio Unitario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 2,
    //     name: "cantidad",
    //     label: "cantidad",
    //     type: "number",
    //     placeholder: "cantidad",
    //     description: "cantidad",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 44,
        name: "item",
        label: "item",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "copias", label: "Copias" },
            { value: "otros", label: "Otros" },
            // { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioTotal",
        label: "Monto de Ingreso S/.",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "comentario",
        label: "comentario",
        type: "text",
        placeholder: "comentario",
        description: "comentario",
        required: false,
        multiline: true,
        rows: 3,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 54,
        name: "numeroFactura",
        label: "Número Factura",
        type: "text",
        placeholder: "numero Factura",
        description: "numero Factura",
        required: false,
        multiline: false,
        rows: 3,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const formOtrosEgresos = [
    {
        id: 0,
        name: "fechaInicio",
        label: "fecha Inicio",
        type: "date",
        placeholder: "fecha Inicio",
        description: "fecha Inicio",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 1,
    //     name: "item",
    //     label: "item",
    //     type: "text",
    //     placeholder: "item",
    //     description: "item",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 3,
    //     name: "precioUnitario",
    //     label: "precio Unitario",
    //     type: "number",
    //     placeholder: "precio Unitario",
    //     description: "precio Unitario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    // {
    //     id: 2,
    //     name: "cantidad",
    //     label: "cantidad",
    //     type: "number",
    //     placeholder: "cantidad",
    //     description: "cantidad",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 44,
        name: "item",
        label: "item",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "bazar", label: "Bazar" },
            { value: "otros", label: "Otros" },
            // { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "precioTotal",
        label: "Monto de Egreso S/.",
        type: "number",
        placeholder: "Total",
        description: "Total",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 5,
        name: "comentario",
        label: "comentario",
        type: "text",
        placeholder: "comentario",
        description: "comentario",
        required: true,
        multiline: true,
        rows: 3,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 54,
        name: "numeroFactura",
        label: "Número Factura",
        type: "text",
        placeholder: "numero Factura",
        description: "numero Factura",
        required: false,
        multiline: false,
        rows: 3,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 6,
        name: "medioPago",
        label: "medio de Pago",
        type: "select",
        // options: ["Disponible", "Ocupada", "Sucia", "No Disponible", "Reservada"],
        options: [
            { value: "0", label: "efectivo" },
            { value: "1", label: "yapes" },
            { value: "2", label: "tarjeta" },
        ],
        placeholder: "medio de Pago",
        description: "medio de Pago",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

// Form crear usuario
export const formCrearUsuario = [
    // {
    //     id: 0,
    //     name: "statusActive",
    //     label: "Status Usuario",
    //     type: "select",
    //     options: [
    //         { value: "1", label: "Activo" },
    //         { value: "0", label: "Inactivo" },
    //     ],
    //     placeholder: "Status Usuario",
    //     description: "Status Usuario",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
    {
        id: 62,
        name: "title",
        label: "Titulo Evento",
        type: "text",
        options: [
            { value: "1", label: "Activo" },
            { value: "0", label: "Inactivo" },
        ],
        placeholder: "Titulo Evento",
        description: "Titulo Evento",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 63,
        name: "dateEvent",
        label: "Fecha Evento",
        type: "date",
        options: [
            { value: "1", label: "Activo" },
            { value: "0", label: "Inactivo" },
        ],
        placeholder: "Fecha Evento",
        description: "Fecha Evento",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 64,
        name: "flyerEvent",
        label: "Flyer Evento",
        type: "file",
        options: [
            { value: "1", label: "Activo" },
            { value: "0", label: "Inactivo" },
        ],
        placeholder: "Flyer Evento",
        description: "Flyer Evento",
        required: false,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 1,
        name: "capacity",
        label: "Capacidad Personas",
        type: "select",
        options: [
            { value: "200", label: "200 Personas" },
            { value: "250", label: "250 Personas" },
            { value: "300", label: "300 Personas" },
        ],
        placeholder: "Capacidad Personas",
        description: "Capacidad Personas",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
]

export const dataComprarTicket = [
    {
        id: 1,
        name: "documentoUsuario",
        label: "Documento Cliente (DNI)",
        type: "number",
        options: [
            { value: "1", label: "Activo" },
            { value: "0", label: "Inactivo" },
        ],
        placeholder: "Documento Cliente",
        description: "Documento Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 2,
        name: "nombres",
        label: "Nombres Cliente",
        type: "text",
        options: [
            { value: "1", label: "Activo" },
            { value: "0", label: "Inactivo" },
        ],
        placeholder: "Nombres Cliente",
        description: "Nombres Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 3,
        name: "apellidoPaterno",
        label: "Apellido Paterno",
        type: "text",
        options: [
            { value: "1", label: "Activo" },
            { value: "0", label: "Inactivo" },
        ],
        placeholder: "Apellido Paterno Cliente",
        description: "Apellido Paterno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    {
        id: 4,
        name: "apellidoMaterno",
        label: "Apellido Materno",
        type: "text",
        options: [
            { value: "1", label: "Activo" },
            { value: "0", label: "Inactivo" },
        ],
        placeholder: "Apellido Materno Cliente",
        description: "Apellido Materno Cliente",
        required: true,
        icon: "fa fa-file-alt",
        color: "bg-blue-500",
    },
    // {
    //     id: 64,
    //     name: "fileUrl",
    //     label: "Seleccione Voucher",
    //     type: "file",
    //     options: [
    //         { value: "1", label: "Activo" },
    //         { value: "0", label: "Inactivo" },
    //     ],
    //     placeholder: "Seleccione Voucher",
    //     description: "Seleccione Voucher",
    //     required: true,
    //     icon: "fa fa-file-alt",
    //     color: "bg-blue-500",
    // },
]
